#
# reiser4/plugin/space/Makefile
#

ifdef CONFIG_REISER4_CHECK
CFLAGS_bitmap.o += -O0
CFLAGS_test.o += -O0
CFLAGS_space_allocator.o += -O0
endif

obj-y	+= bitmap.o test.o space_allocator.o

include $(TOPDIR)/Rules.make
