#include "spinlock.h"

asm(
"\n"
".align	4\n"
".globl	__write_lock_failed\n"
"__write_lock_failed:\n"
"	" LOCK "addl	$" RW_LOCK_BIAS_STR ",(%eax)\n"
"1:	cmpl	$" RW_LOCK_BIAS_STR ",(%eax)\n"
"	jne	1b\n"
"\n"
"	" LOCK "subl	$" RW_LOCK_BIAS_STR ",(%eax)\n"
"	jnz	__write_lock_failed\n"
"	ret\n"
"\n"
"\n"
".align	4\n"
".globl	__read_lock_failed\n"
"__read_lock_failed:\n"
"	lock ; incl	(%eax)\n"
"1:	cmpl	$1,(%eax)\n"
"	js	1b\n"
"\n"
"	lock ; decl	(%eax)\n"
"	js	__read_lock_failed\n"
"	ret\n"
);
