#
# reiser4/plugin/Makefile
#
obj-y	+= object.o hash.o tail_policy.o plugin.o symlink.o

obj-y	+= node/
obj-y	+= item/
obj-y	+= dir/
obj-y	+= file/
obj-y	+= oid/
obj-y	+= space/
obj-y	+= disk_format/
obj-y	+= security/

include $(TOPDIR)/Rules.make
