#!/bin/sh

TESTS="testslpc1-64-rw testslpc1-128-rw testslpc1-256-rw testslpc1-512-rw testslpc1-1024-rw testslpc1-64-ex testslpc1-128-ex testslpc1-256-ex testslpc1-512-ex testslpc1-1024-ex testslpc1-64-no testslpc1-128-no testslpc1-256-no testslpc1-512-no testslpc1-1024-no"

NREPS="1 2 3 4 5"
#NREPS="1"

for t in $TESTS; do
  for r in $NREPS; do
    ./$t
  done
done
