#
# reiser4/plugin/disk_format/Makefile
#

ifdef CONFIG_REISER4_CHECK
CFLAGS_disk_format_40.o += -O0
CFLAGS_test.o += -O0
CFLAGS_disk_format.o += -O0
endif

obj-y	+= disk_format_40.o test.o disk_format.o

include $(TOPDIR)/Rules.make
